services:
  kerberos-agent:
    image: kerberos/agent:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - .env
    volumes:
      - ./agent/config:/home/agent/data/config
      - ./agent/recordings:/home/agent/data/recordings

  visionone-kerberos-collector:
    build: ./visionone-kerberos-collector
    restart: unless-stopped
    depends_on:
      - kerberos-agent
    env_file:
      - .env
    volumes:
      - ./data:/data

